#############################################################################
# Makefile for building: w
# Generated by qmake (3.1) (Qt 6.11.0)
# Project:  w.pro
# Template: app
# Command: C:/Users/asahi/Downloads/msys64/ucrt64/bin/qmake.exe -o Makefile w.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:/Users/asahi/Downloads/msys64/ucrt64/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = C:/Users/asahi/Downloads/msys64/ucrt64/bin/qmake.exe -install qinstall
QINSTALL_PROGRAM = C:/Users/asahi/Downloads/msys64/ucrt64/bin/qmake.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
IDC           = idc
IDL           = widl
ZIP           = 
DEF_FILE      = 
RES_FILE      = 
SED           = sed
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: w.pro ../../Downloads/msys64/ucrt64/share/qt6/mkspecs/win32-g++/qmake.conf ../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/spec_pre.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/device_config.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/common/sanitize.conf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/common/gcc-base.conf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/common/g++-base.conf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/common/windows-vulkan.conf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/common/g++-win32.conf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/common/windows-desktop.conf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/qconfig.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_core.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_core_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_dbus.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_designer.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_entrypoint_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_gui.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_help.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_help_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_linguist.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_network.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_network_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_opengl.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_sql.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_testlib.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_uitools.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_widgets.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_xml.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/qt_functions.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/qt_config.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/win32-g++/qmake.conf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/spec_post.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/exclusive_builds.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/toolchain.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/default_pre.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/win32/default_pre.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/resolve_config.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/exclusive_builds_post.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/default_post.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/precompile_header.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/warn_on.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/permissions.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/qt.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/resources_functions.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/resources.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/moc.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/win32/opengl.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/uic.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/qmake_use.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/file_copies.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/win32/windows.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/testcase_targets.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/exceptions.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/yacc.prf \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/lex.prf \
		w.pro \
		../../Downloads/msys64/ucrt64/lib/Qt6EntryPoint.prl \
		.qmake.stash \
		../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/build_pass.prf
	$(QMAKE) -o Makefile w.pro
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/spec_pre.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/device_config.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/common/sanitize.conf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/common/gcc-base.conf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/common/g++-base.conf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/common/windows-vulkan.conf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/common/g++-win32.conf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/common/windows-desktop.conf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/qconfig.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_concurrent.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_core.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_core_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_dbus.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_designer.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_designer_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_entrypoint_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_gui.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_gui_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_help.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_help_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_linguist.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_network.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_network_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_opengl.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_printsupport.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_sql.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_sql_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_testinternals_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_testlib.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_tools_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_uitools.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_widgets.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_xml.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/modules/qt_lib_xml_private.pri:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/qt_functions.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/qt_config.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/win32-g++/qmake.conf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/spec_post.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/exclusive_builds.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/toolchain.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/default_pre.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/win32/default_pre.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/resolve_config.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/exclusive_builds_post.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/default_post.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/precompile_header.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/warn_on.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/permissions.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/qt.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/resources_functions.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/resources.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/moc.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/win32/opengl.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/uic.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/qmake_use.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/file_copies.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/win32/windows.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/testcase_targets.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/exceptions.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/yacc.prf:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/lex.prf:
w.pro:
../../Downloads/msys64/ucrt64/lib/Qt6EntryPoint.prl:
.qmake.stash:
../../Downloads/msys64/ucrt64/share/qt6/mkspecs/features/build_pass.prf:
qmake: FORCE
	@$(QMAKE) -o Makefile w.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

.SUFFIXES:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
